### ISSUE TITLE
In-Memory cache for downloaded certificates

### ISSUE THREAD

**Issue by vithalreddy** [timokoessler/easy-ocsp#1]
First of all, great work!!!, really simplifies the OCSP.

-   Is your feature request related to a problem?
- yes, we need to check certificate status for millions of request but we can't store certificate anywhere.
-   Describe the solution you'd like.
- https://github.com/timokoessler/easy-ocsp/blob/main/src/tls.ts#L10C17-L10C29 in this fn we can in-memory caching based on user config.
-   Describe alternatives you've considered.
- we cache the status check outside this lib
-   Add any other context about the feature request.
- this feature will help anyone using `getCertStatusByDomain` with each request for checking ocsp status for ex: FEDRamp

**Comment by timokoessler** [comment]
Thanks for creating this issue. Do I understand correctly that you want to cache the certificates? 
To do this, you could call the functions `downloadCert` and `getCertStatus` instead of `getCertStatusByDomain`.
```ts
import { downloadCert, getCertStatus } from 'easy-ocsp';

try {
    // Check if cert is cached ...
    const cert = await downloadCert('example.com'); // Only if cert is not cached
    // Cache cert
    const ocspResult = await getCertStatus(cert);
} catch (e) {
    // Handle errors ...
}
```
I would rather not implement caching in the library itself, as the strategy can depend heavily on the application. For example, the use of an in-memory database such as Redis could be useful in some cases.

**Comment by vithalreddy** [comment]
thanks, this makes sense.
